from pathlib import Path


CORE_DIR = Path(__file__).resolve().parent
PROJECT_DIR = CORE_DIR.parent
WORKSPACE_DIR = PROJECT_DIR.parent

GNEISS_TRAJECTORIES_DIR = WORKSPACE_DIR / "trajectories" / "GNEISS"
GIRAFF_TRAJECTORIES_DIR = WORKSPACE_DIR / "trajectories" / "GIRAFF"
COAST_DIR = PROJECT_DIR / "coast"
RECEIVERS_PATH = WORKSPACE_DIR / "receivers.csv"

GNEISS_LEFT_TRAJECTORY_PATH = GNEISS_TRAJECTORIES_DIR / "36397_GPS_Time_Export_01.csv"
GNEISS_RIGHT_TRAJECTORY_PATH = GNEISS_TRAJECTORIES_DIR / "36398_GPS_Time_Export_00.csv"
GIRAFF_381_TRAJECTORY_PATH = GIRAFF_TRAJECTORIES_DIR / "36381_MAIN_PAYLOAD_GPS.xlsx"
GIRAFF_380_TRAJECTORY_PATH = GIRAFF_TRAJECTORIES_DIR / "36380_MAIN_PAYLOAD_GPS.xlsx"
COAST_LON_PATH = COAST_DIR / "coastlon.txt"
COAST_LAT_PATH = COAST_DIR / "coastlat.txt"


MISSION_TRAJECTORY_PATHS = {
    "GNEISS": {
        "left": GNEISS_LEFT_TRAJECTORY_PATH,
        "right": GNEISS_RIGHT_TRAJECTORY_PATH,
    },
    "GIRAFF": {
        "main": GIRAFF_381_TRAJECTORY_PATH,
    },
}

GIRAFF_TRAJECTORY_PATHS_BY_DATE = {
    "20250202": {
        "main": GIRAFF_381_TRAJECTORY_PATH,
    },
    "20250209": {
        "main": GIRAFF_380_TRAJECTORY_PATH,
    },
}
